name: node-exporter
summary: Exporter for machine metrics.
description: |
  Prometheus exporter for hardware and OS metrics exposed by *NIX kernels,
  written in Go with pluggable metric collectors.

contact: jose.masson@canonical.com
license: Apache-2.0
confinement: strict

base: core24
adopt-info: node-exporter

plugs:
  proc-sys-kernel-random:
    interface: system-files
    read:
      - /proc/buddyinfo
      - /proc/slabinfo
      - /proc/softirqs
      - /proc/sys/kernel/random/poolsize
      - /proc/sys/kernel/random/urandom_min_reseed_secs
      - /proc/sys/kernel/random/write_wakeup_threshold
      - /proc/sys/kernel/threads-max
      - /sys/fs/btrfs
      - /sys/kernel/mm/ksm/full_scans
      - /sys/kernel/mm/ksm/merge_across_nodes
      - /sys/kernel/mm/ksm/pages_shared

parts:
  wrapper:
    plugin: dump
    source: ./snap
    source-type: local
    override-build: |
      cp local/command-wrapper $CRAFT_PART_INSTALL/
  node-exporter:
    plugin: go
    build-snaps: [go/latest/stable]
    source: https://github.com/prometheus/node_exporter.git
    source-type: git
    build-packages:
      - gcc
    override-pull: |
        snapcraftctl pull
        last_committed_tag="$(git describe --tags $(git rev-list --tags --max-count=1))"
        git fetch
        git checkout "${last_committed_tag}"
        [ -n "$(echo ${last_committed_tag} | grep "-")" ] && grade=devel || grade=stable
        snapcraftctl set-version "${last_committed_tag}"
        snapcraftctl set-grade "$grade"
apps:
  node-exporter:
    command: command-wrapper
    daemon: simple
    # need systemd activation support
    # https://github.com/prometheus/node_exporter/issues/1622
    # sockets:
    #   web:
    #     listen-stream: "[::]:9100"
    plugs:
    - login-session-observe
    - network-bind
    - time-control
    - hardware-observe
    - log-observe
    - mount-observe
    - network-observe
    - system-observe
    - proc-sys-kernel-random
